### ISSUE TITLE
Do we really need node to be installed?

### ISSUE THREAD

**Issue by samhatoum** [meteor-velocity/node-soft-mirror#15]
If we used fork instead of spawn [here](https://github.com/meteor-velocity/node-soft-mirror/blob/master/lib/LongRunningChildProcess.coffee#L149) and [here](https://github.com/meteor-velocity/node-soft-mirror/blob/master/lib/spawnScript.js#L37), would that remove the need for users to have node installed and possibly risk the mirror running a different version of node to the master?

**Comment by Sanjo** [comment]
The Meteor provided version of node is now used since 0.2.8.
