### ISSUE TITLE
audit-argument-checks compatibility

### ISSUE THREAD

**Issue by matteodem** [meteor-velocity/node-soft-mirror#28]
I get following error when I add ```mike:mocha``` as a package, which I think has to do with the mirror not checking all it's arguments (audit-argument-checks throws that error)

Exception while invoking method 'velocity/reports/submit' Error: Did not check() all arguments during call to 'velocity/reports/submit'

**Comment by Sanjo** [comment]
Can you report this please in the mike:mocha issues. There is a check and it hasn't been changed for a while: https://github.com/meteor-velocity/velocity/blob/3eef4881dea089cc5a7b82ffd79bbc21c7d6fbef/core.js#L360-L372.
